export * from "./admins";
export * from "./teachers";
export * from "./classes";
export * from "./students";
export * from "./subjects";
export * from "./attendance";
export * from "./grades";
export * from "./audit-logs";
export * from "./announcements";
